name: build

on: [push, pull_request]

jobs:

  ubuntu-22_04:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: apt-update
      run: sudo apt-get update -qq
    - name: apt-install
      run: sudo apt-get install -qq -y --no-install-recommends gir1.2-gtk-3.0 python3-gi python3-gi-cairo python3-numpy python3-setuptools graphviz xvfb
    - name: build
      run: python3 setup.py sdist
    - name: test
      run: .github/scripts/test.sh

  ubuntu-20_04:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: apt-update
      run: sudo apt-get update -qq
    - name: apt-install
      run: sudo apt-get install -qq -y --no-install-recommends gir1.2-gtk-3.0 python3-gi python3-gi-cairo python3-numpy python3-setuptools graphviz xvfb
    - name: build
      run: python3 setup.py sdist
    - name: test
      run: .github/scripts/test.sh
